import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ScanData {
  id: string
  url: string
  domain: string
  riskScore: number
  riskLevel: string
  findings: {
    summary: {
      hasAI: boolean
      riskScore: {
        score: number
        level: string
        grade: string
      }
      criticalIssues: number
      highIssues: number
      mediumIssues: number
      lowIssues: number
    }
    detectedTech: {
      aiProviders: string[]
      chatWidgets: string[]
    }
    findings: Array<{
      id: string
      category: string
      severity: string
      title: string
      description: string
      impact: string
      recommendation: string
    }>
  }
  createdAt: string
  completedAt: string
}

export function generatePDFReport(scan: ScanData): jsPDF {
  const doc = new jsPDF()
  let yPosition = 20

  // Header
  doc.setFontSize(24)
  doc.setTextColor(30, 58, 138) // Blue-900
  doc.text('AI Security Scan Report', 20, yPosition)
  yPosition += 10

  // URL
  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Scanned URL: ${scan.url}`, 20, yPosition)
  yPosition += 15

  // Risk Score Box
  doc.setFillColor(241, 245, 249) // Slate-100
  doc.rect(20, yPosition, 170, 30, 'F')

  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Security Score', 25, yPosition + 10)

  doc.setFontSize(32)
  const scoreColor = getScoreColor(scan.riskScore)
  doc.setTextColor(scoreColor.r, scoreColor.g, scoreColor.b)
  doc.text(`${scan.riskScore}/100`, 120, yPosition + 15)

  doc.setFontSize(14)
  doc.text(`Grade: ${scan.findings.summary.riskScore.grade}`, 120, yPosition + 25)

  yPosition += 40

  // Issue Summary
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Issues Found:', 20, yPosition)
  yPosition += 8

  const issueData = [
    ['Critical', scan.findings.summary.criticalIssues.toString()],
    ['High', scan.findings.summary.highIssues.toString()],
    ['Medium', scan.findings.summary.mediumIssues.toString()],
    ['Low', scan.findings.summary.lowIssues.toString()],
  ]

  autoTable(doc, {
    startY: yPosition,
    head: [['Severity', 'Count']],
    body: issueData,
    theme: 'striped',
    headStyles: { fillColor: [30, 58, 138] },
    margin: { left: 20, right: 20 },
  })

  yPosition = (doc as any).lastAutoTable.finalY + 15

  // Detected AI Technologies
  if (scan.findings.summary.hasAI) {
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('Detected AI Technologies:', 20, yPosition)
    yPosition += 8

    if (scan.findings.detectedTech.aiProviders.length > 0) {
      doc.setFontSize(10)
      doc.setTextColor(60, 60, 60)
      doc.text(`AI Providers: ${scan.findings.detectedTech.aiProviders.join(', ')}`, 25, yPosition)
      yPosition += 6
    }

    if (scan.findings.detectedTech.chatWidgets.length > 0) {
      doc.setFontSize(10)
      doc.text(`Chat Widgets: ${scan.findings.detectedTech.chatWidgets.join(', ')}`, 25, yPosition)
      yPosition += 6
    }

    yPosition += 10
  }

  // Findings Details
  doc.addPage()
  yPosition = 20

  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Security Findings Details', 20, yPosition)
  yPosition += 10

  scan.findings.findings.forEach((finding, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage()
      yPosition = 20
    }

    // Finding box
    const severityColor = getSeverityColor(finding.severity)
    doc.setFillColor(severityColor.bg.r, severityColor.bg.g, severityColor.bg.b)
    doc.rect(20, yPosition, 4, 8, 'F')

    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text(`${index + 1}. ${finding.title}`, 28, yPosition + 6)
    yPosition += 10

    doc.setFontSize(9)
    doc.setTextColor(100, 100, 100)
    doc.text(`Severity: ${finding.severity.toUpperCase()}`, 28, yPosition)
    yPosition += 6

    doc.setFontSize(9)
    doc.setTextColor(60, 60, 60)
    const descLines = doc.splitTextToSize(finding.description, 160)
    doc.text(descLines, 28, yPosition)
    yPosition += descLines.length * 5 + 3

    doc.setFontSize(9)
    doc.setTextColor(80, 80, 80)
    doc.text('Recommendation:', 28, yPosition)
    yPosition += 5
    const recLines = doc.splitTextToSize(finding.recommendation, 160)
    doc.text(recLines, 28, yPosition)
    yPosition += recLines.length * 5 + 8
  })

  // Footer on last page
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Generated by AI Security Scanner | Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  }

  return doc
}

function getScoreColor(score: number): { r: number; g: number; b: number } {
  if (score >= 80) return { r: 34, g: 197, b: 94 } // Green-500
  if (score >= 60) return { r: 234, g: 179, b: 8 } // Yellow-500
  if (score >= 40) return { r: 249, g: 115, b: 22 } // Orange-500
  return { r: 239, g: 68, b: 68 } // Red-500
}

function getSeverityColor(severity: string): {
  bg: { r: number; g: number; b: number }
  text: { r: number; g: number; b: number }
} {
  switch (severity.toLowerCase()) {
    case 'critical':
      return { bg: { r: 254, g: 226, b: 226 }, text: { r: 185, g: 28, b: 28 } }
    case 'high':
      return { bg: { r: 254, g: 243, b: 199 }, text: { r: 234, g: 88, b: 12 } }
    case 'medium':
      return { bg: { r: 254, g: 249, b: 195 }, text: { r: 202, g: 138, b: 4 } }
    case 'low':
      return { bg: { r: 219, g: 234, b: 254 }, text: { r: 30, g: 64, b: 175 } }
    default:
      return { bg: { r: 243, g: 244, b: 246 }, text: { r: 75, g: 85, b: 99 } }
  }
}
